# Generated by Django 5.0 on 2023-12-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
