# Generated by Django 5.0 on 2023-12-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbackend', '0006_orderitem_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
