# Generated by Django 5.0 on 2023-12-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbackend', '0007_remove_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shop',
        ),
    ]
